server:
    port: 8080
---
spring.profiles: local
spring:
    datasource:
        name: vehicles
        driverClassName: org.h2.Driver
        initialize: false
        url: jdbc:h2:mem:vehicles
    devtools:
        add-properties: true
---
spring.profiles: prod
spring:
    devtools:
        add-properties: false